[package]
name = "selection"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
pyo3 = { version = "0.17", features = ["extension-module"] }
rayon = "1.10.0"

[lib]
crate-type = ["cdylib"]
